//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio9_Eje4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        public int IdEqu { get; set; }
        public string CodTipEqu { get; set; }
        public string CodEst { get; set; }
        public string Descripcion { get; set; }
        public string Icono { get; set; }
        public string CodExt { get; set; }
    
        public virtual EstadoEquipo EstadoEquipo { get; set; }
        public virtual TipoEquipo TipoEquipo { get; set; }
    }
}
