//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio9_Eje6.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Lab9_Eje6DBEntities : DbContext
    {
        public Lab9_Eje6DBEntities()
            : base("name=Lab9_Eje6DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<carreras> carreras { get; set; }
        public virtual DbSet<docentes> docentes { get; set; }
        public virtual DbSet<estudiantes> estudiantes { get; set; }
        public virtual DbSet<materias> materias { get; set; }
        public virtual DbSet<matriculas> matriculas { get; set; }
        public virtual DbSet<semestres> semestres { get; set; }
    }
}
