//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio9_Eje6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class materias
    {
        public int id_materia { get; set; }
        public string nombre_materia { get; set; }
        public Nullable<int> carga_horaria { get; set; }
        public int id_carrera { get; set; }
        public Nullable<int> id_docente { get; set; }
    
        public virtual carreras carreras { get; set; }
        public virtual docentes docentes { get; set; }
    }
}
