//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio9_Eje6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class matriculas
    {
        public int id_matricula { get; set; }
        public int id_estudiante { get; set; }
        public int id_carrera { get; set; }
        public int id_semestre { get; set; }
        public Nullable<int> gestion { get; set; }
        public Nullable<System.DateTime> fecha_matricula { get; set; }
    
        public virtual carreras carreras { get; set; }
        public virtual estudiantes estudiantes { get; set; }
        public virtual semestres semestres { get; set; }
    }
}
