//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio9_Eje5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripcion
    {
        public int IdInscripcion { get; set; }
        public int EstudianteId { get; set; }
        public int CursoId { get; set; }
        public Nullable<System.DateTime> FechaInscripcion { get; set; }
        public Nullable<decimal> Calificacion { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Estudiante Estudiante { get; set; }
    }
}
